name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci
        
      - name: Run tests and coverage
        run: npm test -- --coverage
        
      # - name: Run Acceptance tests (Cucumber)
      #   run: npm run cucumber
        
      - name: Run Eslint
        run: npm run lint
    
      - name: Run Build
        run: npm run build
